services:
  db:
    image: postgres:15-alpine
    container_name: spaceship-app-db
    environment:
      POSTGRES_USER: spaceship
      POSTGRES_PASSWORD: to_1nf1n1ty_And_Bey0nd
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U spaceship" ]
      interval: 500ms
      timeout: 3s
      retries: 60
  backend:
    build: .
    container_name: spaceship-app-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spaceship
      SPRING_DATASOURCE_USERNAME: spaceship
      SPRING_DATASOURCE_PASSWORD: to_1nf1n1ty_And_Bey0nd
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
volumes:
  pgdata:
